/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocketmoneymanager.historyandcontrol;

import pocketmoneymanager.transactionmanagement.MoneyManager;
import pocketmoneymanager.transactionmanagement.MoneyRecord;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARUF
 */
public class HistoryFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistoryFrame.class.getName());

    /**
     * Creates new form HistoryFrame
     */
    public HistoryFrame() {
        initComponents();

        loadHistory();
    }

    public void loadHistory() {

        MoneyManager manager = PocketMoneyManager.moneyManager;

        MoneyRecord[] records = manager.getRecords();
        int count = manager.getRecordCount();

        DefaultTableModel model = new DefaultTableModel(
                new Object[]{"Type", "Amount", "Description", "Date"},
                0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        // Show newest transaction first
        for (int i = count - 1; i >= 0; i--) {

            MoneyRecord record = records[i];

            model.addRow(new Object[]{
                record.getRecordType(),
                String.format("%.2f", record.getAmount()),
                record.getDescription(),
                record.getDate()
            });
        }

        historyTable.setModel(model);

        // Make columns easier to read
        historyTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        historyTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        historyTable.getColumnModel().getColumn(2).setPreferredWidth(250);
        historyTable.getColumnModel().getColumn(3).setPreferredWidth(120);

        if (count == 0) {
            return;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        historyTitleLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        historyTable = new javax.swing.JTable();
        deleteButton = new javax.swing.JButton();
        clearSelection = new javax.swing.JButton();
        editButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setFocusable(false);

        historyTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        historyTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        historyTitleLabel.setText("Transaction History");

        closeButton.setBackground(new java.awt.Color(242, 108, 79));
        closeButton.setForeground(new java.awt.Color(255, 255, 255));
        closeButton.setText("Close");
        closeButton.setBorderPainted(false);
        closeButton.setFocusPainted(false);
        closeButton.setFocusable(false);
        closeButton.addActionListener(this::closeButtonActionPerformed);

        historyTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Type", "Amount", "Description", "Date"
            }
        ));
        jScrollPane2.setViewportView(historyTable);

        deleteButton.setBackground(new java.awt.Color(220, 38, 38));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("Delete Selected");
        deleteButton.setBorderPainted(false);
        deleteButton.setFocusPainted(false);
        deleteButton.addActionListener(this::deleteButtonActionPerformed);

        clearSelection.setForeground(new java.awt.Color(2, 132, 199));
        clearSelection.setText("Clear Selection");
        clearSelection.setBorderPainted(false);
        clearSelection.setFocusPainted(false);
        clearSelection.addActionListener(this::clearSelectionActionPerformed);

        editButton.setBackground(new java.awt.Color(79, 70, 229));
        editButton.setForeground(new java.awt.Color(255, 255, 255));
        editButton.setText("Edit Selected");
        editButton.setBorderPainted(false);
        editButton.setFocusPainted(false);
        editButton.addActionListener(this::editButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(historyTitleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(editButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(deleteButton)
                .addGap(83, 83, 83)
                .addComponent(clearSelection)
                .addGap(98, 98, 98)
                .addComponent(closeButton)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(historyTitleLabel)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(closeButton)
                    .addComponent(deleteButton)
                    .addComponent(clearSelection)
                    .addComponent(editButton))
                .addGap(45, 45, 45))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_closeButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        int selectedRow = historyTable.getSelectedRow();

        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a transaction to delete.",
                    "Delete Transaction",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete this transaction?",
                "Delete Transaction",
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.WARNING_MESSAGE
        );

        if (choice != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

// Convert table row to MoneyManager record index
        MoneyManager manager = PocketMoneyManager.moneyManager;

        int recordIndex
                = manager.getRecordCount() - 1 - selectedRow;

// Delete the transaction
        boolean deleted = manager.deleteRecord(recordIndex);

        if (deleted) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Transaction deleted successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            // Reload the table
            loadHistory();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Could not delete transaction.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void clearSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSelectionActionPerformed
        historyTable.clearSelection();
    }//GEN-LAST:event_clearSelectionActionPerformed

    private void editButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButtonActionPerformed
        int selectedRow = historyTable.getSelectedRow();

        if (selectedRow == -1) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please select a transaction to edit.",
                    "Edit Transaction",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        MoneyManager manager = PocketMoneyManager.moneyManager;

        // Table displays newest transaction first,
        // so convert table row to actual record index.
        int recordIndex
                = manager.getRecordCount() - 1 - selectedRow;

        EditTransactionFrame editFrame
                = new EditTransactionFrame(this, recordIndex);

        editFrame.setVisible(true);
    }//GEN-LAST:event_editButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HistoryFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearSelection;
    private javax.swing.JButton closeButton;
    private javax.swing.JButton deleteButton;
    private javax.swing.JButton editButton;
    private javax.swing.JTable historyTable;
    private javax.swing.JLabel historyTitleLabel;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
