/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocketmoneymanager.dashboardandinput;

import pocketmoneymanager.dashboardandinput.DashboardFrame;
import pocketmoneymanager.transactionmanagement.Expense;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import pocketmoneymanager.historyandcontrol.PocketMoneyManager;

/**
 *
 * @author MARUF
 */
public class AddExpenseFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AddExpenseFrame.class.getName());

    /**
     * Creates new form AddExpenseFrame
     */
    private DashboardFrame dashboard;

    public AddExpenseFrame(DashboardFrame dashboard) {
        initComponents();
        this.dashboard = dashboard;

        DateTimeFormatter formatter
                = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        dateField.setText(
                LocalDate.now().format(formatter)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        expenseTitleLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        amountField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        descriptionField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateField = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        expenseTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        expenseTitleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        expenseTitleLabel.setText("Add Expense");

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Amount");

        amountField.setPreferredSize(new java.awt.Dimension(300, 35));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Description");

        descriptionField.setPreferredSize(new java.awt.Dimension(300, 35));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Date");

        dateField.setPreferredSize(new java.awt.Dimension(300, 35));

        addButton.setBackground(new java.awt.Color(231, 76, 60));
        addButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        addButton.setForeground(new java.awt.Color(255, 255, 255));
        addButton.setText("Add Expense");
        addButton.setBorderPainted(false);
        addButton.addActionListener(this::addButtonActionPerformed);

        cancelButton.setBackground(new java.awt.Color(52, 73, 94));
        cancelButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText("Cancel");
        cancelButton.setBorderPainted(false);
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(addButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelButton))
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(amountField, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                    .addComponent(descriptionField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(216, Short.MAX_VALUE))
            .addComponent(expenseTitleLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(expenseTitleLabel)
                .addGap(44, 44, 44)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(amountField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addButton)
                    .addComponent(cancelButton))
                .addContainerGap(156, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        String amountText = amountField.getText().trim();
        String description = descriptionField.getText().trim();
        String date = dateField.getText().trim();

        // Check empty fields
        if (amountText.isEmpty()
                || description.isEmpty()
                || date.isEmpty()) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please fill in all fields.",
                    "Add Expense",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        double amount;

        // Check amount format
        try {

            amount = Double.parseDouble(amountText);

        } catch (NumberFormatException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Please enter a valid amount.",
                    "Add Expense",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );

            return;
        }

        // Check positive amount
        if (amount <= 0) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Amount must be greater than zero.",
                    "Add Expense",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }
        // Validate date format: dd/MM/yyyy
        DateTimeFormatter formatter
                = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        try {

            LocalDate.parse(date, formatter);

        } catch (DateTimeParseException e) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Input the correct format of date.\n"
                    + "Use: dd/MM/yyyy",
                    "Invalid Date",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Get current balance
        double currentBalance
                = PocketMoneyManager.moneyManager.getBalance();

        // Prevent overspending
        if (amount > currentBalance) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    String.format(
                            "Insufficient balance!\n\n"
                            + "Your current balance is: %.2f\n"
                            + "You are trying to spend: %.2f",
                            currentBalance,
                            amount
                    ),
                    "Insufficient Balance",
                    javax.swing.JOptionPane.WARNING_MESSAGE
            );

            return;
        }

        // Create expense
        Expense expense
                = new Expense(amount, description, date);

        // Add expense
        boolean added
                = PocketMoneyManager.moneyManager.addRecord(expense);

        if (added) {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Expense added successfully!",
                    "Success",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
            );

            dashboard.updateDashboard();

            this.dispose();

        } else {

            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Could not add expense.",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }//GEN-LAST:event_addButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        // AddExpenseFrame is opened from DashboardFrame.
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField amountField;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField dateField;
    private javax.swing.JTextField descriptionField;
    private javax.swing.JLabel expenseTitleLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
