/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pocketmoneymanager.dashboardandinput;

import pocketmoneymanager.historyandcontrol.HistoryFrame;
import pocketmoneymanager.historyandcontrol.PocketMoneyManager;
import pocketmoneymanager.usermanagement.LoginFrame;
import pocketmoneymanager.usermanagement.User;

/**
 *
 * @author MARUF
 */
public class DashboardFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DashboardFrame.class.getName());

    /**
     * Creates new form DashboardFrame
     */
    private User currentUser;

    public DashboardFrame(User user) {

        initComponents();

        this.currentUser = user;

        welcomeLabel.setText(
                "Welcome, " + currentUser.getFullName() + "!"
        );

        updateDashboard();
    }

    public void updateDashboard() {

        double balance = PocketMoneyManager.moneyManager.getBalance();
        double allowance = PocketMoneyManager.moneyManager.getTotalAllowance();
        double expenses = PocketMoneyManager.moneyManager.getTotalExpenses();

        balanceLabel.setText(String.format("%.2f", balance));
        allowanceLabel.setText(
                String.format("Allowance: %.2f", allowance)
        );
        expenseLabel.setText(
                String.format("Expenses: %.2f", expenses)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        appNameLabel = new javax.swing.JLabel();
        welcomeLabel = new javax.swing.JLabel();
        balanceTitleLabel = new javax.swing.JLabel();
        balanceLabel = new javax.swing.JLabel();
        allowanceLabel = new javax.swing.JLabel();
        expenseLabel = new javax.swing.JLabel();
        addAllowanceButton = new javax.swing.JButton();
        addExpenseButton = new javax.swing.JButton();
        historyButton = new javax.swing.JButton();
        logoutButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(245, 247, 250));

        appNameLabel.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        appNameLabel.setForeground(new java.awt.Color(30, 58, 138));
        appNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        appNameLabel.setText("POCKET MONEY MANAGER");

        welcomeLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        welcomeLabel.setText("Welcome");

        balanceTitleLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        balanceTitleLabel.setForeground(new java.awt.Color(22, 163, 74));
        balanceTitleLabel.setText("Your Balance");

        balanceLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(22, 163, 74));
        balanceLabel.setText("0.00");

        allowanceLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        allowanceLabel.setText("Allowance: 0.00");

        expenseLabel.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        expenseLabel.setText("Expenses: 0.00");

        addAllowanceButton.setBackground(new java.awt.Color(46, 204, 113));
        addAllowanceButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addAllowanceButton.setForeground(new java.awt.Color(255, 255, 255));
        addAllowanceButton.setText("Add Allowance");
        addAllowanceButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addAllowanceButton.setBorderPainted(false);
        addAllowanceButton.addActionListener(this::addAllowanceButtonActionPerformed);

        addExpenseButton.setBackground(new java.awt.Color(231, 76, 60));
        addExpenseButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addExpenseButton.setForeground(new java.awt.Color(255, 255, 255));
        addExpenseButton.setText("Add Expense");
        addExpenseButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        addExpenseButton.setBorderPainted(false);
        addExpenseButton.addActionListener(this::addExpenseButtonActionPerformed);

        historyButton.setBackground(new java.awt.Color(31, 58, 86));
        historyButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        historyButton.setForeground(new java.awt.Color(255, 255, 255));
        historyButton.setText("Transaction History");
        historyButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        historyButton.setBorderPainted(false);
        historyButton.addActionListener(this::historyButtonActionPerformed);

        logoutButton.setBackground(new java.awt.Color(230, 126, 34));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("Logout");
        logoutButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        logoutButton.setBorderPainted(false);
        logoutButton.addActionListener(this::logoutButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(appNameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(expenseLabel)
                    .addComponent(allowanceLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(balanceTitleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(balanceLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addAllowanceButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addExpenseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(119, 119, 119)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutButton)
                    .addComponent(historyButton))
                .addGap(188, 188, 188))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(appNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(welcomeLabel)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceTitleLabel)
                    .addComponent(balanceLabel))
                .addGap(35, 35, 35)
                .addComponent(allowanceLabel)
                .addGap(18, 18, 18)
                .addComponent(expenseLabel)
                .addGap(77, 77, 77)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addAllowanceButton)
                    .addComponent(historyButton))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addExpenseButton)
                    .addComponent(logoutButton))
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addAllowanceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAllowanceButtonActionPerformed
        AddAllowanceFrame allowanceFrame = new AddAllowanceFrame(this);
        allowanceFrame.setVisible(true);
    }//GEN-LAST:event_addAllowanceButtonActionPerformed

    private void addExpenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addExpenseButtonActionPerformed
        AddExpenseFrame expenseFrame
                = new AddExpenseFrame(this);

        expenseFrame.setVisible(true);
    }//GEN-LAST:event_addExpenseButtonActionPerformed

    private void historyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historyButtonActionPerformed
        HistoryFrame historyFrame
                = new HistoryFrame();

        historyFrame.setVisible(true);
    }//GEN-LAST:event_historyButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int choice = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to logout?",
                "Logout",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (choice == javax.swing.JOptionPane.YES_OPTION) {

            LoginFrame loginFrame = new LoginFrame();
            loginFrame.setVisible(true);

            this.dispose();
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {

            // A real User will be supplied from LoginFrame.
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAllowanceButton;
    private javax.swing.JButton addExpenseButton;
    private javax.swing.JLabel allowanceLabel;
    private javax.swing.JLabel appNameLabel;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JLabel balanceTitleLabel;
    private javax.swing.JLabel expenseLabel;
    private javax.swing.JButton historyButton;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
